import { Alexandria } from "next/font/google";
import "./globals.css";

const Alex = Alexandria({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="dark:bg-[#dbdfe0]">{children}</body>
    </html>
  );
}
